FROM php:8.0.28-apache


# Instalar extensiones adicionales
RUN docker-php-ext-install mysqli

# Copiar tu aplicación al directorio de trabajo
COPY ./carro /var/www/html/

EXPOSE 80

# Cambiar los permisos si es necesario
# RUN chown -R www-data:www-data /var/www/html/

# Habilitar el módulo de Apache si es necesario
# RUN a2enmod rewrite

# Reiniciar Apache
# RUN service apache2 restart



# Puedes necesitar otras configuraciones dependiendo de tu aplicación

# CMD ["apache2-foreground"]

